import React, { useState } from 'react';
import { 
  X, 
  Share2, 
  Send, 
  CheckCircle2, 
  ExternalLink, 
  IndianRupee, 
  Smartphone,
  ArrowRight
} from 'lucide-react';
import confetti from 'canvas-confetti';

export default function WhatsAppPreviewModal({ theme, isOpen, onClose }) {
  const [isSent, setIsSent] = useState(false);
  const [isPaid, setIsPaid] = useState(false);

  if (!isOpen) return null;

  const handlePay = () => {
    setIsPaid(true);
    try {
      confetti({
        particleCount: 50,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#00B9F1', '#002E6E', '#10B981']
      });
    } catch (e) {}
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-fadeIn">
      <div className="bg-white dark:bg-[#0a0a0a] rounded-3xl max-w-md w-full border-2 border-neutral-300 dark:border-neutral-800 p-6 shadow-2xl relative">
        
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full bg-neutral-100 hover:bg-neutral-200 dark:bg-neutral-800 dark:hover:bg-neutral-700 text-black dark:text-white transition-all"
        >
          <X className="w-4 h-4" />
        </button>

        {/* Modal Header */}
        <div className="flex items-center gap-3 mb-5">
          <div className="p-2.5 rounded-2xl bg-[#00B9F1]/15 text-[#00B9F1] border border-[#00B9F1]/40">
            <Smartphone className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-black text-black dark:text-white">
              Autonomous WhatsApp 1-Tap UPI
            </h3>
            <p className="text-xs text-neutral-500 font-medium">
              Generated by Collector Agent via n8n
            </p>
          </div>
        </div>

        {/* WhatsApp Phone Mockup Screen */}
        <div className="rounded-2xl bg-[#efeae2] dark:bg-[#0b141a] border border-neutral-300 dark:border-neutral-800 p-4 space-y-3 font-sans">
          
          {/* WhatsApp Chat Header */}
          <div className="flex items-center gap-2.5 pb-2 border-b border-neutral-300 dark:border-neutral-800">
            <div className="w-8 h-8 rounded-full bg-black text-[#00B9F1] font-black flex items-center justify-center text-xs border border-[#00B9F1]/40">
              SG
            </div>
            <div>
              <div className="text-xs font-black text-black dark:text-white">Sharma General Store</div>
              <div className="text-[10px] text-emerald-600 dark:text-emerald-400 font-bold">Verified Merchant</div>
            </div>
          </div>

          {/* Outgoing Message Bubble */}
          <div className="p-3.5 rounded-2xl bg-[#d9fdd3] dark:bg-[#005c4b] text-black dark:text-white text-xs space-y-2 max-w-[92%] ml-auto rounded-tr-none shadow">
            <p className="leading-relaxed font-medium">
              नमस्ते सुरेश जी, आपके किराने के बिल का <strong>₹1,200</strong> बकाया है। कृपया नीचे दिए गए 1-टैप UPI लिंक से भुगतान करें:
            </p>

            {/* Dynamic UPI 1-Tap Action Pill */}
            <div className="p-2.5 rounded-xl bg-white dark:bg-black/80 border border-emerald-300 dark:border-emerald-700 flex items-center justify-between shadow-sm">
              <div>
                <span className="text-[10px] text-black dark:text-[#00B9F1] font-mono font-black block">
                  UPI Instant Pay
                </span>
                <span className="text-sm font-black text-black dark:text-white">₹1,200.00</span>
              </div>

              {!isPaid ? (
                <button
                  onClick={handlePay}
                  className="px-3 py-1.5 rounded-lg electric-glow-btn text-black font-black text-xs shadow flex items-center gap-1 active:scale-95"
                >
                  <span>Pay Now</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              ) : (
                <span className="text-xs font-black text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                  <CheckCircle2 className="w-4 h-4" /> Paid!
                </span>
              )}
            </div>

            <div className="text-[9px] text-right text-neutral-500 dark:text-emerald-200 font-medium">
              09:02 AM • Delivered
            </div>
          </div>

          {/* Simulated Payment Success Callback */}
          {isPaid && (
            <div className="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-400 dark:border-emerald-500/40 text-emerald-800 dark:text-emerald-300 text-xs animate-fadeIn space-y-1">
              <div className="font-bold flex items-center gap-1.5 text-black dark:text-white">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                <span>UPI Webhook Received: ₹1,200 Cleared!</span>
              </div>
              <p className="text-[11px] text-neutral-600 dark:text-neutral-300 font-medium">
                Ledger updated automatically in Postgres. Soundbox announcement queued.
              </p>
            </div>
          )}

        </div>

        {/* Footer info */}
        <div className="mt-4 flex items-center justify-between text-xs text-neutral-500 font-medium">
          <span>WhatsApp Cloud API Simulation</span>
          <button
            onClick={onClose}
            className="text-black dark:text-[#00B9F1] font-black hover:underline"
          >
            Close Preview
          </button>
        </div>

      </div>
    </div>
  );
}
